"""upgrade database tables

Revision ID: 0db50924a7fd
Revises: d3f209a038c6
Create Date: 2025-06-02 18:45:01.558775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db50924a7fd'
down_revision: Union[str, None] = 'd3f209a038c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('team_home_id', sa.UUID(), nullable=False),
    sa.Column('team_away_id', sa.UUID(), nullable=False),
    sa.Column('score_home', sa.Integer(), nullable=False),
    sa.Column('score_away', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_unique_constraint(None, 'chats', ['match_id'])
    op.create_foreign_key(None, 'chats', 'matches', ['match_id'], ['match_id'])
    op.create_foreign_key(None, 'comments', 'matches', ['match_id'], ['match_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='unique')
    op.drop_table('matches')
    # ### end Alembic commands ###
