"""upgrade database tables

Revision ID: 0db50924a7fd
Revises: d3f209a038c6
Create Date: 2025-06-02 18:45:01.558775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db50924a7fd'
down_revision: Union[str, None] = 'd3f209a038c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # REMOVIDO: op.create_table('matches', ...)
    # A tabela 'matches' já foi criada na migração d3f209a038c6

    # Apenas adicionar as constraints e foreign keys
    op.create_unique_constraint(None, 'chats', ['match_id'])
    op.create_foreign_key(None, 'chats', 'matches', ['match_id'], ['match_id'])
    op.create_foreign_key(None, 'comments', 'matches', ['match_id'], ['match_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='unique')
    # REMOVIDO: op.drop_table('matches')
    # A tabela será removida na migração d3f209a038c6 durante o downgrade
    # ### end Alembic commands ###