"""alter_matches_make_start_time_nullable

Revision ID: <NOVO_ID_GERADO_PELO_ALEMBIC>
Revises: d3f209a038c6
Create Date: <DATA_ATUAL>

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '<NOVO_ID_GERADO_PELO_ALEMBIC>' # Substitua pelo ID real
down_revision: Union[str, None] = 'd3f209a038c6' # ID da migração anterior que criou a tabela
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Make start_time nullable in matches table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'start_time',
               existing_type=sa.DateTime(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert start_time to not nullable in matches table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'start_time',
               existing_type=sa.DateTime(timezone=True),
               nullable=False)
    # ### end Alembic commands ###