"""add match table

Revision ID: d3f209a038c6
Revises: e8a98499c78c
Create Date: 2025-06-02 16:49:53.649535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f209a038c6'
down_revision: Union[str, None] = 'e8a98499c78c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
                    sa.Column('match_id', sa.UUID(as_uuid=True), nullable=False),
                    sa.Column('team_home_id', sa.UUID(as_uuid=True), nullable=False),
                    sa.Column('team_away_id', sa.UUID(as_uuid=True), nullable=False),
                    sa.Column('score_home', sa.Integer(), nullable=False),
                    sa.Column('score_away', sa.Integer(), nullable=False),
                    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('status', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('match_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###